name: Deploy
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Check Node version
              run: node -v

            - name: Install Dependencies
              run: npm install

            - name: Generate Environment Variables File for Production
              env:
                VITE_API_URL: ${{ secrets.VITE_API_URL }}
                VITE_SAMPLE: ${{ secrets.VITE_SAMPLE }}
              run: |
                echo "VITE_API_URL=${VITE_API_URL}" >> .env
                echo "VITE_SAMPLE=${VITE_SAMPLE}" >> .env

            - name: Build
              run: npm run build

            - name: zip create
              run: | 
                cp appspec.yml deploy.sh ./dist/
                zip -qq -r ./build-fe.zip ./dist
              shell: bash

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Upload to S3
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: |
                  aws s3 cp --region ap-northeast-2 ./build-fe.zip s3://${{ secrets.S3_BUCKET_NAME }}/build-fe.zip

            - name: Deploy
              run: aws deploy create-deployment
                  --application-name DevStep
                  --deployment-config-name CodeDeployDefault.AllAtOnce
                  --deployment-group-name DevStep_deploy_v1
                  --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},key=build-fe.zip,bundleType=zip
